//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.22 at 03:58:53 PM PDT 
//


package org.cinergi.alternative.metadata;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.cinergi.alternative.metadata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.cinergi.alternative.metadata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link Metadata.Metainfo }
     * 
     */
    public Metadata.Metainfo createMetadataMetainfo() {
        return new Metadata.Metainfo();
    }

    /**
     * Create an instance of {@link Metadata.Metainfo.Metc }
     * 
     */
    public Metadata.Metainfo.Metc createMetadataMetainfoMetc() {
        return new Metadata.Metainfo.Metc();
    }

    /**
     * Create an instance of {@link Metadata.Metainfo.Metc.Cntinfo }
     * 
     */
    public Metadata.Metainfo.Metc.Cntinfo createMetadataMetainfoMetcCntinfo() {
        return new Metadata.Metainfo.Metc.Cntinfo();
    }

    /**
     * Create an instance of {@link Metadata.Distinfo }
     * 
     */
    public Metadata.Distinfo createMetadataDistinfo() {
        return new Metadata.Distinfo();
    }

    /**
     * Create an instance of {@link Metadata.Distinfo.Stdorder }
     * 
     */
    public Metadata.Distinfo.Stdorder createMetadataDistinfoStdorder() {
        return new Metadata.Distinfo.Stdorder();
    }

    /**
     * Create an instance of {@link Metadata.Distinfo.Stdorder.Digform }
     * 
     */
    public Metadata.Distinfo.Stdorder.Digform createMetadataDistinfoStdorderDigform() {
        return new Metadata.Distinfo.Stdorder.Digform();
    }

    /**
     * Create an instance of {@link Metadata.Distinfo.Stdorder.Digform.Digtopt }
     * 
     */
    public Metadata.Distinfo.Stdorder.Digform.Digtopt createMetadataDistinfoStdorderDigformDigtopt() {
        return new Metadata.Distinfo.Stdorder.Digform.Digtopt();
    }

    /**
     * Create an instance of {@link Metadata.Distinfo.Stdorder.Digform.Digtopt.Onlinopt }
     * 
     */
    public Metadata.Distinfo.Stdorder.Digform.Digtopt.Onlinopt createMetadataDistinfoStdorderDigformDigtoptOnlinopt() {
        return new Metadata.Distinfo.Stdorder.Digform.Digtopt.Onlinopt();
    }

    /**
     * Create an instance of {@link Metadata.Distinfo.Stdorder.Digform.Digtopt.Onlinopt.Computer }
     * 
     */
    public Metadata.Distinfo.Stdorder.Digform.Digtopt.Onlinopt.Computer createMetadataDistinfoStdorderDigformDigtoptOnlinoptComputer() {
        return new Metadata.Distinfo.Stdorder.Digform.Digtopt.Onlinopt.Computer();
    }

    /**
     * Create an instance of {@link Metadata.Distinfo.Distrib }
     * 
     */
    public Metadata.Distinfo.Distrib createMetadataDistinfoDistrib() {
        return new Metadata.Distinfo.Distrib();
    }

    /**
     * Create an instance of {@link Metadata.Distinfo.Distrib.Cntinfo }
     * 
     */
    public Metadata.Distinfo.Distrib.Cntinfo createMetadataDistinfoDistribCntinfo() {
        return new Metadata.Distinfo.Distrib.Cntinfo();
    }

    /**
     * Create an instance of {@link Metadata.Eainfo }
     * 
     */
    public Metadata.Eainfo createMetadataEainfo() {
        return new Metadata.Eainfo();
    }

    /**
     * Create an instance of {@link Metadata.Dataqual }
     * 
     */
    public Metadata.Dataqual createMetadataDataqual() {
        return new Metadata.Dataqual();
    }

    /**
     * Create an instance of {@link Metadata.Dataqual.Lineage }
     * 
     */
    public Metadata.Dataqual.Lineage createMetadataDataqualLineage() {
        return new Metadata.Dataqual.Lineage();
    }

    /**
     * Create an instance of {@link Metadata.Dataqual.Lineage.Procstep }
     * 
     */
    public Metadata.Dataqual.Lineage.Procstep createMetadataDataqualLineageProcstep() {
        return new Metadata.Dataqual.Lineage.Procstep();
    }

    /**
     * Create an instance of {@link Metadata.Dataqual.Lineage.Procstep.Proccont }
     * 
     */
    public Metadata.Dataqual.Lineage.Procstep.Proccont createMetadataDataqualLineageProcstepProccont() {
        return new Metadata.Dataqual.Lineage.Procstep.Proccont();
    }

    /**
     * Create an instance of {@link Metadata.Dataqual.Lineage.Procstep.Proccont.Cntinfo }
     * 
     */
    public Metadata.Dataqual.Lineage.Procstep.Proccont.Cntinfo createMetadataDataqualLineageProcstepProccontCntinfo() {
        return new Metadata.Dataqual.Lineage.Procstep.Proccont.Cntinfo();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo }
     * 
     */
    public Metadata.Idinfo createMetadataIdinfo() {
        return new Metadata.Idinfo();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Ptcontac }
     * 
     */
    public Metadata.Idinfo.Ptcontac createMetadataIdinfoPtcontac() {
        return new Metadata.Idinfo.Ptcontac();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Ptcontac.Cntinfo }
     * 
     */
    public Metadata.Idinfo.Ptcontac.Cntinfo createMetadataIdinfoPtcontacCntinfo() {
        return new Metadata.Idinfo.Ptcontac.Cntinfo();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Thelayid }
     * 
     */
    public Metadata.Idinfo.Thelayid createMetadataIdinfoThelayid() {
        return new Metadata.Idinfo.Thelayid();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Thelayid.Layrname }
     * 
     */
    public Metadata.Idinfo.Thelayid.Layrname createMetadataIdinfoThelayidLayrname() {
        return new Metadata.Idinfo.Thelayid.Layrname();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Keywords }
     * 
     */
    public Metadata.Idinfo.Keywords createMetadataIdinfoKeywords() {
        return new Metadata.Idinfo.Keywords();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Spdom }
     * 
     */
    public Metadata.Idinfo.Spdom createMetadataIdinfoSpdom() {
        return new Metadata.Idinfo.Spdom();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Timeperd }
     * 
     */
    public Metadata.Idinfo.Timeperd createMetadataIdinfoTimeperd() {
        return new Metadata.Idinfo.Timeperd();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Timeperd.Timeinfo }
     * 
     */
    public Metadata.Idinfo.Timeperd.Timeinfo createMetadataIdinfoTimeperdTimeinfo() {
        return new Metadata.Idinfo.Timeperd.Timeinfo();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Citation }
     * 
     */
    public Metadata.Idinfo.Citation createMetadataIdinfoCitation() {
        return new Metadata.Idinfo.Citation();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Citation.Citeinfo }
     * 
     */
    public Metadata.Idinfo.Citation.Citeinfo createMetadataIdinfoCitationCiteinfo() {
        return new Metadata.Idinfo.Citation.Citeinfo();
    }

    /**
     * Create an instance of {@link Metadata.Spdoinfo }
     * 
     */
    public Metadata.Spdoinfo createMetadataSpdoinfo() {
        return new Metadata.Spdoinfo();
    }

    /**
     * Create an instance of {@link Metadata.Metainfo.Metextns }
     * 
     */
    public Metadata.Metainfo.Metextns createMetadataMetainfoMetextns() {
        return new Metadata.Metainfo.Metextns();
    }

    /**
     * Create an instance of {@link Metadata.Metainfo.Metc.Cntinfo.Cntorgp }
     * 
     */
    public Metadata.Metainfo.Metc.Cntinfo.Cntorgp createMetadataMetainfoMetcCntinfoCntorgp() {
        return new Metadata.Metainfo.Metc.Cntinfo.Cntorgp();
    }

    /**
     * Create an instance of {@link Metadata.Metainfo.Metc.Cntinfo.Cntaddr }
     * 
     */
    public Metadata.Metainfo.Metc.Cntinfo.Cntaddr createMetadataMetainfoMetcCntinfoCntaddr() {
        return new Metadata.Metainfo.Metc.Cntinfo.Cntaddr();
    }

    /**
     * Create an instance of {@link Metadata.Distinfo.Stdorder.Digform.Digtinfo }
     * 
     */
    public Metadata.Distinfo.Stdorder.Digform.Digtinfo createMetadataDistinfoStdorderDigformDigtinfo() {
        return new Metadata.Distinfo.Stdorder.Digform.Digtinfo();
    }

    /**
     * Create an instance of {@link Metadata.Distinfo.Stdorder.Digform.Digtopt.Onlinopt.Computer.Networka }
     * 
     */
    public Metadata.Distinfo.Stdorder.Digform.Digtopt.Onlinopt.Computer.Networka createMetadataDistinfoStdorderDigformDigtoptOnlinoptComputerNetworka() {
        return new Metadata.Distinfo.Stdorder.Digform.Digtopt.Onlinopt.Computer.Networka();
    }

    /**
     * Create an instance of {@link Metadata.Distinfo.Distrib.Cntinfo.Cntorgp }
     * 
     */
    public Metadata.Distinfo.Distrib.Cntinfo.Cntorgp createMetadataDistinfoDistribCntinfoCntorgp() {
        return new Metadata.Distinfo.Distrib.Cntinfo.Cntorgp();
    }

    /**
     * Create an instance of {@link Metadata.Distinfo.Distrib.Cntinfo.Cntaddr }
     * 
     */
    public Metadata.Distinfo.Distrib.Cntinfo.Cntaddr createMetadataDistinfoDistribCntinfoCntaddr() {
        return new Metadata.Distinfo.Distrib.Cntinfo.Cntaddr();
    }

    /**
     * Create an instance of {@link Metadata.Eainfo.Overview }
     * 
     */
    public Metadata.Eainfo.Overview createMetadataEainfoOverview() {
        return new Metadata.Eainfo.Overview();
    }

    /**
     * Create an instance of {@link Metadata.Dataqual.Attracc }
     * 
     */
    public Metadata.Dataqual.Attracc createMetadataDataqualAttracc() {
        return new Metadata.Dataqual.Attracc();
    }

    /**
     * Create an instance of {@link Metadata.Dataqual.Lineage.Procstep.Proccont.Cntinfo.Cntorgp }
     * 
     */
    public Metadata.Dataqual.Lineage.Procstep.Proccont.Cntinfo.Cntorgp createMetadataDataqualLineageProcstepProccontCntinfoCntorgp() {
        return new Metadata.Dataqual.Lineage.Procstep.Proccont.Cntinfo.Cntorgp();
    }

    /**
     * Create an instance of {@link Metadata.Dataqual.Lineage.Procstep.Proccont.Cntinfo.Cntaddr }
     * 
     */
    public Metadata.Dataqual.Lineage.Procstep.Proccont.Cntinfo.Cntaddr createMetadataDataqualLineageProcstepProccontCntinfoCntaddr() {
        return new Metadata.Dataqual.Lineage.Procstep.Proccont.Cntinfo.Cntaddr();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Descript }
     * 
     */
    public Metadata.Idinfo.Descript createMetadataIdinfoDescript() {
        return new Metadata.Idinfo.Descript();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Status }
     * 
     */
    public Metadata.Idinfo.Status createMetadataIdinfoStatus() {
        return new Metadata.Idinfo.Status();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Browse }
     * 
     */
    public Metadata.Idinfo.Browse createMetadataIdinfoBrowse() {
        return new Metadata.Idinfo.Browse();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Progaff }
     * 
     */
    public Metadata.Idinfo.Progaff createMetadataIdinfoProgaff() {
        return new Metadata.Idinfo.Progaff();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Ptcontac.Cntinfo.Cntorgp }
     * 
     */
    public Metadata.Idinfo.Ptcontac.Cntinfo.Cntorgp createMetadataIdinfoPtcontacCntinfoCntorgp() {
        return new Metadata.Idinfo.Ptcontac.Cntinfo.Cntorgp();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Ptcontac.Cntinfo.Cntaddr }
     * 
     */
    public Metadata.Idinfo.Ptcontac.Cntinfo.Cntaddr createMetadataIdinfoPtcontacCntinfoCntaddr() {
        return new Metadata.Idinfo.Ptcontac.Cntinfo.Cntaddr();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Thelayid.Layrname.Theme }
     * 
     */
    public Metadata.Idinfo.Thelayid.Layrname.Theme createMetadataIdinfoThelayidLayrnameTheme() {
        return new Metadata.Idinfo.Thelayid.Layrname.Theme();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Keywords.Theme }
     * 
     */
    public Metadata.Idinfo.Keywords.Theme createMetadataIdinfoKeywordsTheme() {
        return new Metadata.Idinfo.Keywords.Theme();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Keywords.Place }
     * 
     */
    public Metadata.Idinfo.Keywords.Place createMetadataIdinfoKeywordsPlace() {
        return new Metadata.Idinfo.Keywords.Place();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Keywords.Stratum }
     * 
     */
    public Metadata.Idinfo.Keywords.Stratum createMetadataIdinfoKeywordsStratum() {
        return new Metadata.Idinfo.Keywords.Stratum();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Spdom.Bounding }
     * 
     */
    public Metadata.Idinfo.Spdom.Bounding createMetadataIdinfoSpdomBounding() {
        return new Metadata.Idinfo.Spdom.Bounding();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Timeperd.Timeinfo.Rngdates }
     * 
     */
    public Metadata.Idinfo.Timeperd.Timeinfo.Rngdates createMetadataIdinfoTimeperdTimeinfoRngdates() {
        return new Metadata.Idinfo.Timeperd.Timeinfo.Rngdates();
    }

    /**
     * Create an instance of {@link Metadata.Idinfo.Citation.Citeinfo.Pubinfo }
     * 
     */
    public Metadata.Idinfo.Citation.Citeinfo.Pubinfo createMetadataIdinfoCitationCiteinfoPubinfo() {
        return new Metadata.Idinfo.Citation.Citeinfo.Pubinfo();
    }

}
