//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.20 at 09:34:23 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.isotc211.org/2005/gmx", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.isotc211._2005.gmx;
