//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.20 at 09:34:23 PM PDT 
//


package org.isotc211._2005.srv;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.isotc211._2005.gco.AbstractObjectType;
import org.isotc211._2005.gco.TypeNamePropertyType;


/**
 * <p>Java class for SV_Interface_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SV_Interface_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.isotc211.org/2005/gco}AbstractObject_Type">
 *       &lt;sequence>
 *         &lt;element name="typeName" type="{http://www.isotc211.org/2005/gco}TypeName_PropertyType"/>
 *         &lt;element name="operation" type="{http://www.isotc211.org/2005/srv}SV_Operation_PropertyType"/>
 *         &lt;element name="theSV_PortSpecification" type="{http://www.isotc211.org/2005/srv}SV_PortSpecification_PropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SV_Interface_Type", propOrder = {
    "typeName",
    "operation",
    "theSVPortSpecification"
})
public class SVInterfaceType
    extends AbstractObjectType
{

    @XmlElement(required = true)
    protected TypeNamePropertyType typeName;
    @XmlElement(required = true)
    protected SVOperationPropertyType operation;
    @XmlElement(name = "theSV_PortSpecification")
    protected SVPortSpecificationPropertyType theSVPortSpecification;

    /**
     * Gets the value of the typeName property.
     * 
     * @return
     *     possible object is
     *     {@link TypeNamePropertyType }
     *     
     */
    public TypeNamePropertyType getTypeName() {
        return typeName;
    }

    /**
     * Sets the value of the typeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeNamePropertyType }
     *     
     */
    public void setTypeName(TypeNamePropertyType value) {
        this.typeName = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link SVOperationPropertyType }
     *     
     */
    public SVOperationPropertyType getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SVOperationPropertyType }
     *     
     */
    public void setOperation(SVOperationPropertyType value) {
        this.operation = value;
    }

    /**
     * Gets the value of the theSVPortSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link SVPortSpecificationPropertyType }
     *     
     */
    public SVPortSpecificationPropertyType getTheSVPortSpecification() {
        return theSVPortSpecification;
    }

    /**
     * Sets the value of the theSVPortSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link SVPortSpecificationPropertyType }
     *     
     */
    public void setTheSVPortSpecification(SVPortSpecificationPropertyType value) {
        this.theSVPortSpecification = value;
    }

}
