//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.20 at 09:34:23 PM PDT 
//


package org.isotc211._2005.srv;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SV_PlatformNeutralServiceSpecification_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SV_PlatformNeutralServiceSpecification_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.isotc211.org/2005/srv}AbstractSV_AbstractServiceSpecification_Type">
 *       &lt;sequence>
 *         &lt;element name="serviceType" type="{http://www.isotc211.org/2005/srv}SV_ServiceType_PropertyType"/>
 *         &lt;element name="implSpec" type="{http://www.isotc211.org/2005/srv}SV_PlatformSpecificServiceSpecification_PropertyType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SV_PlatformNeutralServiceSpecification_Type", propOrder = {
    "serviceType",
    "implSpec"
})
public class SVPlatformNeutralServiceSpecificationType
    extends AbstractSVAbstractServiceSpecificationType
{

    @XmlElement(required = true)
    protected SVServiceTypePropertyType serviceType;
    @XmlElement(required = true)
    protected List<SVPlatformSpecificServiceSpecificationPropertyType> implSpec;

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link SVServiceTypePropertyType }
     *     
     */
    public SVServiceTypePropertyType getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SVServiceTypePropertyType }
     *     
     */
    public void setServiceType(SVServiceTypePropertyType value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the implSpec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the implSpec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImplSpec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SVPlatformSpecificServiceSpecificationPropertyType }
     * 
     * 
     */
    public List<SVPlatformSpecificServiceSpecificationPropertyType> getImplSpec() {
        if (implSpec == null) {
            implSpec = new ArrayList<SVPlatformSpecificServiceSpecificationPropertyType>();
        }
        return this.implSpec;
    }

}
