//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.20 at 09:34:23 PM PDT 
//


package org.isotc211._2005.srv;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.isotc211._2005.gco.AbstractObjectType;


/**
 * <p>Java class for SV_Service_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SV_Service_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.isotc211.org/2005/gco}AbstractObject_Type">
 *       &lt;sequence>
 *         &lt;element name="specification" type="{http://www.isotc211.org/2005/srv}SV_PlatformSpecificServiceSpecification_PropertyType" maxOccurs="unbounded"/>
 *         &lt;element name="theSV_Port" type="{http://www.isotc211.org/2005/srv}SV_Port_PropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SV_Service_Type", propOrder = {
    "specification",
    "theSVPort"
})
public class SVServiceType
    extends AbstractObjectType
{

    @XmlElement(required = true)
    protected List<SVPlatformSpecificServiceSpecificationPropertyType> specification;
    @XmlElement(name = "theSV_Port")
    protected List<SVPortPropertyType> theSVPort;

    /**
     * Gets the value of the specification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SVPlatformSpecificServiceSpecificationPropertyType }
     * 
     * 
     */
    public List<SVPlatformSpecificServiceSpecificationPropertyType> getSpecification() {
        if (specification == null) {
            specification = new ArrayList<SVPlatformSpecificServiceSpecificationPropertyType>();
        }
        return this.specification;
    }

    /**
     * Gets the value of the theSVPort property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the theSVPort property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTheSVPort().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SVPortPropertyType }
     * 
     * 
     */
    public List<SVPortPropertyType> getTheSVPort() {
        if (theSVPort == null) {
            theSVPort = new ArrayList<SVPortPropertyType>();
        }
        return this.theSVPort;
    }

}
