//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.20 at 09:34:23 PM PDT 
//


package org.isotc211._2005.gco;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.isotc211._2005.gmi.AbstractMIGeolocationInformationType;
import org.isotc211._2005.gmi.LEAlgorithmType;
import org.isotc211._2005.gmi.LEProcessStepReportType;
import org.isotc211._2005.gmi.LEProcessingType;
import org.isotc211._2005.gmi.MIAcquisitionInformationType;
import org.isotc211._2005.gmi.MIEventType;
import org.isotc211._2005.gmi.MIGCPType;
import org.isotc211._2005.gmi.MIInstrumentType;
import org.isotc211._2005.gmi.MIObjectiveType;
import org.isotc211._2005.gmi.MIOperationType;
import org.isotc211._2005.gmi.MIPlanType;
import org.isotc211._2005.gmi.MIPlatformPassType;
import org.isotc211._2005.gmi.MIPlatformType;
import org.isotc211._2005.gmi.MIRangeElementDescriptionType;
import org.isotc211._2005.gmi.MIRequestedDateType;
import org.isotc211._2005.gmi.MIRequirementType;
import org.isotc211._2005.gmi.MISensorTypeCodeType;
import org.isotc211._2005.gmx.AbstractCTCatalogueType;
import org.isotc211._2005.gmx.AbstractMXFileType;
import org.isotc211._2005.srv.AbstractSVAbstractServiceSpecificationType;
import org.isotc211._2005.srv.SVCoupledResourceType;
import org.isotc211._2005.srv.SVInterfaceType;
import org.isotc211._2005.srv.SVOperationChainMetadataType;
import org.isotc211._2005.srv.SVOperationChainType;
import org.isotc211._2005.srv.SVOperationMetadataType;
import org.isotc211._2005.srv.SVOperationType;
import org.isotc211._2005.srv.SVParameterType;
import org.isotc211._2005.srv.SVPortSpecificationType;
import org.isotc211._2005.srv.SVPortType;
import org.isotc211._2005.srv.SVServiceType;
import org.isotc211.iso19139.d_2007_04_17.gmd.AbstractDQElementType;
import org.isotc211.iso19139.d_2007_04_17.gmd.AbstractDQResultType;
import org.isotc211.iso19139.d_2007_04_17.gmd.AbstractDSAggregateType;
import org.isotc211.iso19139.d_2007_04_17.gmd.AbstractEXGeographicExtentType;
import org.isotc211.iso19139.d_2007_04_17.gmd.AbstractMDContentInformationType;
import org.isotc211.iso19139.d_2007_04_17.gmd.AbstractMDIdentificationType;
import org.isotc211.iso19139.d_2007_04_17.gmd.AbstractMDSpatialRepresentationType;
import org.isotc211.iso19139.d_2007_04_17.gmd.AbstractRSReferenceSystemType;
import org.isotc211.iso19139.d_2007_04_17.gmd.CIAddressType;
import org.isotc211.iso19139.d_2007_04_17.gmd.CICitationType;
import org.isotc211.iso19139.d_2007_04_17.gmd.CIContactType;
import org.isotc211.iso19139.d_2007_04_17.gmd.CIDateType;
import org.isotc211.iso19139.d_2007_04_17.gmd.CIOnlineResourceType;
import org.isotc211.iso19139.d_2007_04_17.gmd.CIResponsiblePartyType;
import org.isotc211.iso19139.d_2007_04_17.gmd.CISeriesType;
import org.isotc211.iso19139.d_2007_04_17.gmd.CITelephoneType;
import org.isotc211.iso19139.d_2007_04_17.gmd.DQDataQualityType;
import org.isotc211.iso19139.d_2007_04_17.gmd.DQScopeType;
import org.isotc211.iso19139.d_2007_04_17.gmd.DSAssociationType;
import org.isotc211.iso19139.d_2007_04_17.gmd.DSDataSetType;
import org.isotc211.iso19139.d_2007_04_17.gmd.EXExtentType;
import org.isotc211.iso19139.d_2007_04_17.gmd.EXTemporalExtentType;
import org.isotc211.iso19139.d_2007_04_17.gmd.EXVerticalExtentType;
import org.isotc211.iso19139.d_2007_04_17.gmd.LILineageType;
import org.isotc211.iso19139.d_2007_04_17.gmd.LIProcessStepType;
import org.isotc211.iso19139.d_2007_04_17.gmd.LISourceType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDAggregateInformationType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDApplicationSchemaInformationType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDBrowseGraphicType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDConstraintsType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDDigitalTransferOptionsType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDDimensionType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDDistributionType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDDistributorType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDExtendedElementInformationType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDFormatType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDGeometricObjectsType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDIdentifierType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDKeywordsType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDMaintenanceInformationType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDMediumType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDMetadataExtensionInformationType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDMetadataType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDPortrayalCatalogueReferenceType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDRangeDimensionType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDReferenceSystemType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDRepresentativeFractionType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDStandardOrderProcessType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDUsageType;
import org.isotc211.iso19139.d_2007_04_17.gmd.PTFreeTextType;
import org.isotc211.iso19139.d_2007_04_17.gmd.PTLocaleType;


/**
 * <p>Java class for AbstractObject_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractObject_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.isotc211.org/2005/gco}ObjectIdentification"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractObject_Type")
@XmlSeeAlso({
    MIGCPType.class,
    MIAcquisitionInformationType.class,
    LEAlgorithmType.class,
    MIRangeElementDescriptionType.class,
    MIRequirementType.class,
    LEProcessStepReportType.class,
    MIEventType.class,
    MIOperationType.class,
    MISensorTypeCodeType.class,
    LEProcessingType.class,
    AbstractMIGeolocationInformationType.class,
    MIInstrumentType.class,
    LIProcessStepType.class,
    LISourceType.class,
    MIPlatformPassType.class,
    MIPlatformType.class,
    MDRangeDimensionType.class,
    MIObjectiveType.class,
    MDMetadataType.class,
    MIRequestedDateType.class,
    MIPlanType.class,
    TypeNameType.class,
    MultiplicityRangeType.class,
    MultiplicityType.class,
    MemberNameType.class,
    MDDimensionType.class,
    LILineageType.class,
    DQDataQualityType.class,
    CIContactType.class,
    MDApplicationSchemaInformationType.class,
    MDPortrayalCatalogueReferenceType.class,
    MDBrowseGraphicType.class,
    MDFormatType.class,
    CIDateType.class,
    DSAssociationType.class,
    AbstractRSReferenceSystemType.class,
    AbstractMDContentInformationType.class,
    MDUsageType.class,
    MDMaintenanceInformationType.class,
    EXTemporalExtentType.class,
    MDReferenceSystemType.class,
    MDIdentifierType.class,
    MDDistributionType.class,
    AbstractMDSpatialRepresentationType.class,
    CITelephoneType.class,
    CISeriesType.class,
    MDDistributorType.class,
    CIResponsiblePartyType.class,
    DQScopeType.class,
    AbstractEXGeographicExtentType.class,
    EXVerticalExtentType.class,
    EXExtentType.class,
    CIOnlineResourceType.class,
    AbstractDQResultType.class,
    MDDigitalTransferOptionsType.class,
    PTLocaleType.class,
    PTFreeTextType.class,
    MDGeometricObjectsType.class,
    MDMediumType.class,
    MDKeywordsType.class,
    CICitationType.class,
    MDExtendedElementInformationType.class,
    MDMetadataExtensionInformationType.class,
    MDConstraintsType.class,
    CIAddressType.class,
    MDAggregateInformationType.class,
    MDStandardOrderProcessType.class,
    AbstractDQElementType.class,
    MDRepresentativeFractionType.class,
    AbstractMXFileType.class,
    AbstractDSAggregateType.class,
    DSDataSetType.class,
    AbstractCTCatalogueType.class,
    SVServiceType.class,
    AbstractMDIdentificationType.class,
    SVInterfaceType.class,
    SVOperationChainMetadataType.class,
    SVPortSpecificationType.class,
    SVCoupledResourceType.class,
    SVOperationType.class,
    SVParameterType.class,
    SVOperationMetadataType.class,
    AbstractSVAbstractServiceSpecificationType.class,
    SVPortType.class,
    SVOperationChainType.class
})
public abstract class AbstractObjectType {

    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "uuid")
    protected String uuid;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUuid(String value) {
        this.uuid = value;
    }

}
